// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjrT-muTA0j6v4r5wrAkQDJwFQbs5Bwwc',
    appId: '1:939708766306:web:71224f5cff3a227835193b',
    messagingSenderId: '939708766306',
    projectId: 'e-commerce-be6aa',
    authDomain: 'e-commerce-be6aa.firebaseapp.com',
    storageBucket: 'e-commerce-be6aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBQaMCiQOm2RHMFNhfu57i3UZWq_chVtI',
    appId: '1:939708766306:android:2e292700a34b712635193b',
    messagingSenderId: '939708766306',
    projectId: 'e-commerce-be6aa',
    storageBucket: 'e-commerce-be6aa.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjrT-muTA0j6v4r5wrAkQDJwFQbs5Bwwc',
    appId: '1:939708766306:web:69b40b89410e4ebd35193b',
    messagingSenderId: '939708766306',
    projectId: 'e-commerce-be6aa',
    authDomain: 'e-commerce-be6aa.firebaseapp.com',
    storageBucket: 'e-commerce-be6aa.appspot.com',
  );
}
